### ISSUE TITLE
download_data.py "No healthy IP available for the backend"

### ISSUE THREAD

**Issue by loicsauteur** [guiwitz/PyImageCourse#1]
Hi @guiwitz 
I just wanted to try out your course (thanks a lot for making this available).
But I failed installing the data part, due to a lost link in your download_data.py file.
It is following link:
`url = 'https://img.myswitzerland.com/671846/407'  `

which gave me following error:
`[...]$ python installation/download_data.py `
`Traceback (most recent call last):`
`File "installation/download_data.py", line 14, in <module> urllib.request.urlretrieve(url, where_to_save+'Klee.jpg')`
`File "/anaconda3/envs/improc_env/lib/python3.6/urllib/request.py", line 248, in urlretrieve with contextlib.closing(urlopen(url, data)) as fp:`
`File "/anaconda3/envs/improc_env/lib/python3.6/urllib/request.py", line 223, in urlopen return opener.open(url, data, timeout)`
`File "/anaconda3/envs/improc_env/lib/python3.6/urllib/request.py", line 532, in open response = meth(req, response)`
`File "/anaconda3/envs/improc_env/lib/python3.6/urllib/request.py", line 642, in http_response 'http', request, response, code, msg, hdrs)`
`File "/anaconda3/envs/improc_env/lib/python3.6/urllib/request.py", line 570, in error return self._call_chain(*args)`
`File "/anaconda3/envs/improc_env/lib/python3.6/urllib/request.py", line 504, in _call_chain result = func(*args)`
`File "/anaconda3/envs/improc_env/lib/python3.6/urllib/request.py", line 650, in http_error_default raise HTTPError(req.full_url, code, msg, hdrs, fp)`
`urllib.error.HTTPError: HTTP Error 503: No healthy IP available for the backend`

I hope you can fix this, I am looking forward to follow your course!
Bests,
Loïc

**Comment by guiwitz** [comment]
Hi Loïc,
as the link is broken, I replaced the picture with another one from Wikipedia so it should work now. Note that if you are mainly interested in bioimage processing, my more recent course for NEUBIAS (https://github.com/guiwitz/neubias_academy_biapy) focuses more on that aspect and runs on both mybinder and Google Colab if you want to avoid installation.
Cheers,
Guillaume

**Comment by loicsauteur** [comment]
Thanks a lot.
I will also check out your Neubias course/video.
Bests
